### ISSUE TITLE
Não esta rodando

### ISSUE THREAD

**Issue by marlon33** [luizmarcus/PHP#2]
Fiz exatamente como no tutotial 
http://luizmarcus.com/php/como-criar-um-bot-para-o-telegram-em-php-parte-1/
http://luizmarcus.com/php/como-criar-um-bot-para-o-telegram-em-php-parte-2/
http://luizmarcus.com/php/como-criar-um-bot-para-o-telegram-em-php-parte-3

https://luizmarcus.com/php/criando-um-bot-para-o-telegram-utilizando-o-wit-ai/

Mas não consegui fazer funcionar no meu
![image](https://user-images.githubusercontent.com/41172965/80892983-c3756f80-8ca4-11ea-82d2-b15ae468cb8f.png)

Porem no seu roda de boa

![image](https://user-images.githubusercontent.com/41172965/80892987-d425e580-8ca4-11ea-97c3-d6e297050997.png)

conseguiria me dar uma auxilio?

**Comment by luizmarcus** [comment]
@marlon33 , 
Como você está customizando o código e são muitas etapas para fazer o bot funcionar com o Witai, vou dar umas dicas que podem te ajudar a solucionar o problema:

1. Estava faltando uma ' (aspa simples) no final da linha define('BOT_TOKEN', 'SEUTOKEN);. O correto é define('BOT_TOKEN', 'SEUTOKEN');. Já fiz a correção no [index.php](https://github.com/luizmarcus/PHP/blob/master/witaitelegrambot/index.php).

2. Confira se o TOKEN do bot está igual ao gerado no BotFather.

2. Verifique se o webhook do seu bot foi setado através da url: https://api.telegram.org/bot(SEU_TOKEN)/setwebhook?url=https://(SUA_URL)/seubot.php. Não esqueça que ela deve suportar o HTTPS.

3. Teste o bot antes de integrá-lo ao Witai. Verifique se ele responde a algum comando simples.

4. O post que detalha a criação e o treinamento do bot no Witai é esse: [https://luizmarcus.com/inovacao/como-criar-um-bot-utilizando-o-wit-ai/](https://luizmarcus.com/inovacao/como-criar-um-bot-utilizando-o-wit-ai/). Dá uma lida e vê se não faltou alguma etapa.

5. Após criar o bot no Witai, sugiro que você realize uma requisição GET para ele usando o Postman, por exemplo, para observar se a resposta é retornada corretamente.

6. Caso você copie e utilize o código do repositório [witaitelegrambot](https://github.com/luizmarcus/PHP/blob/master/witaitelegrambot), você precisa trocar o WITAITOKEN pelo token do seu projeto no Witai. Além disso, no método checkConfidence, você deve adaptar o código para ler as suas entidades.

Espero ter ajudado.

**Comment by marlon33** [comment]
Opa amigo, obrigado por responder, então eu segui os passos certinho, procurando em forum na gringa eu consegui um link de verificação /getWebhookInfo onde o msm me retorna isso
{"ok":true,"result":{"url":"https://www.meusitetop.com/telegramBot/index.php","has_custom_certificate":false,"pending_update_count":1,"last_error_date":1588574891,"last_error_message":"Wrong response from the webhook: 500 Internal Server Error","max_connections":40}}

e não consegui sair mais disso, vc já teve algo do tipo?

**Comment by marlon33** [comment]
não sei como, mas "futricando" consegui arrumar, mas agora so fica dando resultado não encontrado, mas gostei, estou coneguindo montar do jeito q eu quero, mt obg.
![image](https://user-images.githubusercontent.com/41172965/80948193-02501600-8dc8-11ea-9220-b1db7c1fd948.png)


Será que tem haver pq o link agora e ghtml e não html como antes?
https://g1.globo.com/loterias/megasena.ghtml

**Comment by luizmarcus** [comment]
Que bom que funcionou, @marlon33 .

O [parser do exemplo](https://github.com/luizmarcus/PHP/blob/master/witaitelegrambot/parser.php) esta funcionando. Verifica se o html da página está realmente sendo obtido.
