### ISSUE TITLE
consegue me ajudar com parse_mode

### ISSUE THREAD

**Issue by marlon33** [luizmarcus/PHP#3]
Olá consegue me ajudar com parse_mode para enviar msg em html, tipo italico, bold...

**Comment by luizmarcus** [comment]
@marlon33 ,
Dá uma olhada na documentação do Telegram. O link abaixo pode te ajudar:

[https://core.telegram.org/bots/api#formatting-options](https://core.telegram.org/bots/api#formatting-options)

Boa sorte com seu bot! =)
